name: superprojectv2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^1.10.18
  flutter_riverpod: ^2.4.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  uuid: ^4.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:

